const projectActionTypes = {
  GET_USER_PROJECTS_START: "GET_USER_PROJECTS_START",
  GET_USER_PROJECTS_SUCCESS: "GET_USER_PROJECTS_SUCCESS",
  GET_USER_PROJECTS_FAILED: "GET_USER_PROJECTS_FAILED",
  ADD_PROJECT_SUCCESS: "ADD_PROJECT_SUCCESS",
  DELETE_PROJECT_SUCCESS: "DELETE_PROJECT_SUCCESS",
  EDIT_PROJECT_SUCCESS: "EDIT_PROJECT_SUCCESS",
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  EDIT_TASK_SUCCESS: "EDIT_TASK_SUCCES",
  CLEAR_PROJECTS: "CLEAR_PROJECTS"
};

export default projectActionTypes;
